"""add pdf_url to paper

Revision ID: 31daedca6f12
Revises: 5826c9522a3e
Create Date: 2026-07-20 22:00:41.276445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31daedca6f12'
down_revision: Union[str, Sequence[str], None] = '5826c9522a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'pdf_url')
    # ### end Alembic commands ###
