"""Add conversation details

Revision ID: afee60d63ac8
Revises: 31daedca6f12
Create Date: 2026-07-21 10:06:19.500329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afee60d63ac8'
down_revision: Union[str, Sequence[str], None] = '31daedca6f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('query', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('content', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('papers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'papers')
    op.drop_column('conversations', 'content')
    op.drop_column('conversations', 'query')
    # ### end Alembic commands ###
